### ISSUE TITLE
"Cannot find type `size_t` in this scope" when building

### ISSUE THREAD

**Issue by JesseTG** [max-m/rust-libretro#1] opened 2022-12-28 18:44 UTC
I'm attempting to build a local copy of this repo, but I keep getting errors relating to the type [`size_t`](https://docs.rs/rust-libretro-sys/0.1.5/rust_libretro_sys/type.size_t.html) being missing. It looks like it's not consistently being generated by bindgen; is there any reason not to use the type provided by `libc` instead?

**Comment by max-m** [comment] 2022-12-31 02:58
Hi,
at first I could not reproduce this issue on my system, but while working on incorporating the last couple of upstream updates of the `libretro.h` I ran into this problem as well after a run of `cargo clean`.

I’ve pushed some updates to the [dev](https://github.com/max-m/rust-libretro/tree/dev) branch.
Those changes also include the change from `size_t` to `usize` as per https://github.com/rust-lang/rust-bindgen/commit/cc78b6fdb6e829e5fb8fa1639f2182cb49333569.
This should hopefully fix this issue.

**Comment by max-m** [comment] 2023-01-03 00:12
I’ve bumped the version to 0.2.x and published the update on crates.io.
The bump from 0.1.x to 0.2.x happened due to the `size_t` -> `usize` changes, which affected some function signatures.

If you can confirm that building this version works fine on your end I’ll close this issue. :)

**Comment by JesseTG** [comment] 2023-01-03 18:43
Thank you! I want to finish troubleshooting something on my branch, then I'll merge these new commits into it. After that, I'll submit a PR with my Vulkan additions.

**Comment by max-m** [comment] 2023-01-10 19:21
I’ll close this issue as fixed by https://github.com/max-m/rust-libretro/commit/2cf0599effcb226fa6d8f736517058e5244d420f.

**Closed as completed by max-m** 2023-01-10 19:21 UTC
